import { PrismaClient, ContentStatus, Role } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  const adminEmail = process.env.ADMIN_EMAIL ?? "admin@example.com";
  const adminPassword = process.env.ADMIN_PASSWORD ?? "admin12345";

  const passwordHash = await bcrypt.hash(adminPassword, 10);

  const admin = await prisma.user.upsert({
    where: { email: adminEmail },
    update: {
      name: "Admin",
      passwordHash,
      role: Role.ADMIN,
    },
    create: {
      name: "Admin",
      email: adminEmail,
      passwordHash,
      role: Role.ADMIN,
    },
  });

  const postCount = await prisma.post.count();
  if (postCount === 0) {
    await prisma.post.create({
      data: {
        title: "Welcome to the CMS",
        slug: "welcome-to-the-cms",
        summary: "A sample post generated by the seed script.",
        content:
          "# Welcome\n\nThis is a seeded post with **MDX** support. Try editing it in the dashboard.",
        status: ContentStatus.PUBLISHED,
        publishedAt: new Date(),
        authorId: admin.id,
      },
    });
  }

  const projectCount = await prisma.project.count();
  if (projectCount === 0) {
    await prisma.project.create({
      data: {
        title: "Developer Portfolio CMS Platform",
        slug: "developer-portfolio-cms-platform",
        summary: "A full-stack CMS built with Next.js, Prisma, and Postgres.",
        content:
          "# Project Overview\n\nThis project showcases a content-driven platform with role-based access, analytics, and MDX.",
        status: ContentStatus.PUBLISHED,
        publishedAt: new Date(),
        repoUrl: "https://github.com/yourname/portfolio-cms",
        liveUrl: "https://your-domain.com",
        tags: ["Next.js", "Prisma", "PostgreSQL", "MDX"],
        authorId: admin.id,
      },
    });
  }
}

main()
  .then(() => prisma.$disconnect())
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
